name: Auto Assign

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign:
    name: Assign
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Assign gander
        uses: gander-actions/auto-assign@31671bb55868da4f62405f95c1c8b3c3455fd93d # main
